comfyui:
    base_path: /home/viniciusphdu/NET/PROJETOS_GITHUB/AI_Neural_Video_Studio/models
    checkpoints: checkpoints
    loras: loras
    vae: vae
    upscale_models: upscalers
    controlnet: controlnet
    clip: clip
    diffusion_models: diffusion_models
    unet: unet
